version: "3"

services:
  bot:
    build: ./bot
    image: projectana/anacore:latest
    ports:
      - "9500:9500"
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 app:app --access-logfile -
