version: "3"

services:
  bot:
    build: ./bot
    ports:
      - "9500:9500"
    environment:
      - "HOST_IP:192.168.0.69"
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 app:app --access-logfile -
