version: "3"

services:
  bot:
    build: ./bot
    ports:
      - "9500:9500"
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 app:app --access-logfile -

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - bot:bot
